theme: minima
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/colematt" }
    - { platform: google_scholar,  user_url: "https://scholar.google.com/citations?user=GfQ-ozgAAAAJ&hl=en" }
    - { platform: keybase,  user_url: "https://keybase.io/colematthew" }
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/matthewcole4/" }

author:
  name: Matthew Cole
  email: "mcole8@binghamton.edu"
