title: Matthew Cole's Homepage
author:
  name: Matthew Cole
  email: "mcole8@binghamton.edu"
description: > # this means to ignore newlines until the next key  Homepage for Matthew Cole, a PhD candidate at Binghamton University.
  Includes a curriculum vitae, publications, and blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: <!--more-->
show_excerpts: true # set to true to show excerpts on the homepage

theme: minima
minima:
  date_format: "%b %-d, %Y"
  # skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/colematt" }
    - { platform: google_scholar,  user_url: "https://scholar.google.com/citations?user=GfQ-ozgAAAAJ&hl=en" }
    - { platform: keybase,  user_url: "https://keybase.io/colematthew" }
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/matthewcole4/" }
  #  - { platform: orcid, user_url: "https://orcid.org/0000-0003-1743-1504"}

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.markdown
  - publications.markdown
  - teaching.markdown
  - documents.markdown

# Include keybase identity
include: [".well-known"]

plugins:
 - jekyll-feed
